felis/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from ajax_select import urls as ajax_select_urls

urlpatterns = [
	url(r'^', include('employees.urls')),
    url(r'^accounts/', include('employees.urls')),
    url(r'^leaves/', include('leaves.urls')),
    url(r'^trips/', include('trips.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^messages/', include('postman.urls', namespace="postman",
        app_name="postman")),
    url(r'^calendar/', include('calendarium.urls')),
    url(r'^autocomplete/', include(ajax_select_urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

trips/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^trip/', views.TripsListView.as_view(paginate_by=10)),
	url(r'^(?P<pk>[0-9]+)/', views.TripsDetailView.as_view(), name='trip'),
	url(r'^add_trip/', views.add_trip),
	url(r'^add_employee/(?P<pk>[0-9]+)/', views.AddEmployeeFormView.as_view()),
	url(r'^settlement/(?P<pk>[0-9]+)/', views.SettlementListView.as_view(),
		name='settlement'),
	url(r'^add_route/(?P<pk>[0-9]+)/', views.AddRouteFormView.as_view()),
	url(r'^delete_route/(?P<rev>[0-9]+)/(?P<pk>[0-9]+)/',
		views.DeleteRouteView.as_view()),
	url(r'^add_allowance/(?P<pk>[0-9]+)/',
		views.AddAllowanceFormView.as_view()),
	url(r'^delete_allowance/(?P<rev>[0-9]+)/(?P<pk>[0-9]+)/',
		views.DeleteAllowanceView.as_view()),
	url(r'^update_allowance/(?P<rev>[0-9]+)/(?P<pk>[0-9]+)/',
		views.UpdateAllowanceView.as_view()),
	#url(r'^add_fare/(?P<pk>[0-9]+)/', views.AddFareFormView.as_view()),
	url(r'^add_cost/(?P<pk>[0-9]+)/(?P<type>[0-3]{1})/',
		views.AddCostFormView.as_view()),
	#url(r'^add_milage/(?P<pk>[0-9]+)/', views.AddMilageFormView.as_view()),
	#url(r'^add_other/(?P<pk>[0-9]+)/', views.AddOtherFormView.as_view()),
	url(r'^delete_cost/(?P<rev>[0-9]+)/(?P<pk>[0-9]+)/',
		views.DeleteCostView.as_view()),
	url(r'^send/(?P<pk>[0-9]+)/', views.SendView.as_view()),
]

trips/models.py
#-*- coding: utf-8 -*-

from django.contrib.auth.models import User
from django.utils.encoding import python_2_unicode_compatible
from django.db.models.signals import post_save
from django.db import models
import datetime
from assets.models import Car

@python_2_unicode_compatible
class BusinessTrip(models.Model):
    purpose = models.CharField('Cel wyjazdu', max_length=255)
    begin_date = models.DateField('Rozpoczęcie')
    description = models.TextField('Opis', blank=True)
    
    def __str__(self):
        return self.purpose
        
    class Meta:
        verbose_name = 'Delegacja'
        verbose_name_plural = 'Delegacje'
        ordering = ['-begin_date']


STATUS_CHOICES = (
    ('w', 'Oczekuje'),
    ('a', 'Zaakceptowany'),
    ('r', 'Odrzucony'),
)
    
@python_2_unicode_compatible
class BusinessTripEmployee(models.Model):
    employee = models.ForeignKey(User, verbose_name='Pracownik')
    business_trip = models.ForeignKey(BusinessTrip, verbose_name='Delegacja')
    begin_date = models.DateField('Data początkowa')
    end_date = models.DateField('Data końcowa')
    estimated_cost = models.DecimalField('Szacunkowy koszt [zł]',
        max_digits=9, decimal_places=2)
    description = models.TextField('Uzasadnienie', blank=True)
    status = models.CharField('Decyzja', max_length=1, choices=STATUS_CHOICES,
        default='w')

    def _trip_count(self):
        t = BusinessTripEmployee.objects.filter(status='a',
            employee=self.employee).count()
        return t

    _trip_count.short_description = 'odbytych delegacji'
    trip_count = property(_trip_count)

    def _settlement_count(self):
        s = BusinessTripEmployee.objects.filter(
            settlement__status='a', employee=self.employee).count()
        return s

    _settlement_count.short_description = 'rozliczonych delegacji'
    settlement_count = property(_settlement_count)
    
    def __str__(self):
        return "{1} - {0}".format(self.employee.username, self.business_trip.__str__())
        
    class Meta:
        verbose_name = 'Wyjazd służbowy'
        verbose_name_plural = 'Wyjazdy służbowe'
        unique_together = ('employee', 'business_trip',)

def create_settlement(sender, instance, created, **kwargs):
    if created:
        BusinessTripSettlement.objects.create(trip_employee=instance)

post_save.connect(create_settlement, sender=BusinessTripEmployee)


SETTLEMENT_CHOICES = (
    ('i', 'Wprowadzanie'),
    ('w', 'Oczekuje'),
    ('a', 'Rozliczono'),
    ('r', 'Odrzucono'),
)

@python_2_unicode_compatible
class BusinessTripSettlement(models.Model):
    trip_employee = models.OneToOneField(BusinessTripEmployee,
        verbose_name='Wyjazd', related_name='settlement')
    status = models.CharField('Decyzja', max_length=1,
        choices=SETTLEMENT_CHOICES, default='i')

    @property
    def commute_lump_total(self):
        settlement_entries = BusinessTripAllowance.objects.filter(
            settlement=self.pk,
        )
        commute_lump = 0
        for entry in settlement_entries:
            commute_lump += entry.commute_lump
        return commute_lump

    @property
    def accomodation_lump_total(self):
        settlement_entries = BusinessTripAllowance.objects.filter(
            settlement=self.pk,
        )
        accomodation_lump = 0
        for entry in settlement_entries:
            accomodation_lump += entry.accomodation_lump
        return accomodation_lump

    @property
    def allowance_total(self):
        settlement_entries = BusinessTripAllowance.objects.filter(
            settlement=self.pk,
        )
        allowance = 0
        for entry in settlement_entries:
            allowance += entry.allowance
        return allowance

    @property
    def total_total(self):
        settlement_entries = BusinessTripAllowance.objects.filter(
            settlement=self.pk,
        )
        total = 0
        for entry in settlement_entries:
            total += entry.total_allowance
        return total

    @property
    def invoice_total(self):
        settlement_entries = BusinessTripInvoice.objects.filter(
            settlement=self.pk,
        )
        amount = 0
        for entry in settlement_entries:
            amount += entry.amount
        return amount

    @property
    def settlement_total(self):
        return float(self.total_total) + float(self.invoice_total)
    
    def __str__(self):
        return self.trip_employee.__str__()
        
    class Meta:
        verbose_name = 'Rozliczenie'
        verbose_name_plural = 'Rozliczenia'


TRANSPORT_TYPE = (
    ('c', 'samochód firmowy'),
    ('o', 'samochód prywatny'),
    ('r', 'pasażer'),
    ('p', 'komunkacja publiczna'),
    ('t', 'pociąg'),
    ('a', 'samolot'),
)

@python_2_unicode_compatible
class BusinessTripRoute(models.Model):
    settlement = models.ForeignKey(BusinessTripSettlement,
        verbose_name='Rozliczenie')
    begin = models.CharField('Miejsce początkowe', max_length=255)
    begin_time = models.DateTimeField('Początek wyjazdu')
    end = models.CharField('Miejsce docelowe', max_length=255)
    end_time = models.DateTimeField('Koniec wyjazdu')
    transportation = models.CharField('Środek transportu', max_length=1,
        choices=TRANSPORT_TYPE)

    def __str__(self):
        return u"{0} - {1}".format(self.begin, self.end)
        
    class Meta:
        verbose_name = 'Przejazd'
        verbose_name_plural = 'Przejazdy'


BASE_ALLOWANCE = 30
COMMUTE_QUOTE = 0.2
ACCOMODATION_QUOTE = 1.5

@python_2_unicode_compatible
class BusinessTripAllowance(models.Model):
    settlement = models.ForeignKey(BusinessTripSettlement, verbose_name="Rozliczenie")
    begin_time = models.DateTimeField('Początek')
    end_time = models.DateTimeField('Koniec')
    is_first_day = models.BooleanField('Pierwszy dzień delegacji', default=True)
    is_breakfast = models.BooleanField('Śniadanie')
    is_dinner = models.BooleanField('Obiad')
    is_supper= models.BooleanField('Kolacja')
    is_commute_lump = models.BooleanField('Ryczałt za dojazdy')
    is_accomodation_lump = models.BooleanField('Ryczałt za noclegi')

    def _commute_lump(self, base=BASE_ALLOWANCE, quote=COMMUTE_QUOTE):
        return base * quote if self.is_commute_lump else 0
    
    _commute_lump.short_description = 'Ryczałt za dojazdy'
    commute_lump = property(_commute_lump)


    def _accomodation_lump(self, base=BASE_ALLOWANCE, quote=ACCOMODATION_QUOTE):
        return base * quote if self.is_accomodation_lump else 0

    _accomodation_lump.short_description = 'Ryczałt za noclegi'
    accomodation_lump = property(_accomodation_lump)

    def _board_quote(self):
        """
        Oblicza procentową należność z tytułu delegacji w zależności od
        dostępnych posiłków.
        """
        quote = 1

        if self.is_breakfast:
            quote -= 0.25
        if self.is_dinner:
            quote -= 0.5  
        if self.is_supper:
            quote -= 0.25 

        return quote

    def _duration_quote(self):
        """
        Oblicza należność z tytułu delegacji w zależności od czasu jej trwania.

        Dla pierwszego dnia delegacji: 
        - do 8 godzin - 0%
        - powyżej 8 godzin, do 12 godzin - 50%
        - powyżej 12 godzin - 100%

        Dla kolejnych dni:
        - do 8 godzin - 50%
        - powyżej 8 godzin - 100%
        """

        try:
            duration = abs(self.end_time - self.begin_time).total_seconds() / 3600
        except:
            duration = 0    #Adding new blank entity result in error if not set

        if self.is_first_day:
            if duration > 8 and duration <= 12:
                quote = 0.5
            elif duration > 12:
                quote = 1
            else:
                quote = 0
        else:
            if duration <= 8:
                quote = 0.5
            else:
                quote = 1

        return quote

    def _allowance(self, base=BASE_ALLOWANCE):
        return base * self._board_quote() * self._duration_quote()

    _allowance.short_description = 'Dieta'
    allowance = property(_allowance)

    def _total_allowance(self):
        return self._allowance() + self._commute_lump() + self._accomodation_lump()

    _total_allowance.short_description = 'Ogółem'
    total_allowance = property(_total_allowance)


    def __str__(self):
        return "{0} - {1}".format(self.begin_time.strftime('%Y-%m-%d %H:%M'),
            self.end_time.strftime("%Y-%m-%d %H:%M"))

    class Meta:
        verbose_name = 'Dieta'
        verbose_name_plural = 'Diety'
        ordering = ['begin_time',]


@python_2_unicode_compatible
class BusinessTripInvoice(models.Model):
    settlement = models.ForeignKey(BusinessTripSettlement,
        verbose_name="Rozliczenie")
    name = models.CharField('Nazwa', max_length=255)
    amount = models.DecimalField('Kwota', max_digits=9, decimal_places=2,
        default=0) # Milage needs default or blank to work 
    desc = models.TextField('Opis', blank=True)

    def __str__(self):
        return u"{0} - {1}".format(self.name, self.amount)

    class Meta:
        verbose_name = 'Koszt'
        verbose_name_plural = 'Koszty'

def file_name(instance, filename):
    return '/'.join(['content', instance.user.id, filename])

class BusinessTripInvoiceFare(BusinessTripInvoice):
    route = models.ForeignKey(BusinessTripRoute, verbose_name='Trasa')
    scan = models.ImageField(upload_to='content/%Y/%m/%d')

    class Meta:
        verbose_name = 'Koszt podróży'
        verbose_name_plural = 'Koszty podróży'

class BusinessTripInvoiceAccomodation(BusinessTripInvoice):
    overnight = models.ForeignKey(BusinessTripAllowance, verbose_name='Nocleg')
    scan = models.ImageField(upload_to='content/%Y/%m/%d')

    class Meta:
        verbose_name = 'Koszt noclegu'
        verbose_name_plural = 'Koszty noclegu'

class BusinessTripInvoiceOther(BusinessTripInvoice):
    scan = models.ImageField(upload_to='content/%Y/%m/%d')

    class Meta:

trips/forms.py
#-*- coding: utf-8 -*-

from django import forms
from django.forms import ModelForm
from datetime import datetime
from datetimewidget.widgets import DateTimeWidget, DateWidget

from .models import (BusinessTripRoute, BusinessTripAllowance,
	BusinessTripInvoiceFare, BusinessTripInvoiceAccomodation,
	BusinessTripInvoiceOther, BusinessTripInvoiceMilage,
	BusinessTripEmployee)

dateTimeOptions = {
		'format': 'yyyy-mm-dd hh:ii',
		'bootstrap_version': 3,
		'clearBtn': True,
		'weekStart': 1,
		'todayHighlight': True,
	}

dateOptions = {
		'format': 'yyyy-mm-dd',
		'bootstrap_version': 3,
		'clearBtn': True,
		'weekStart': 1,
		'todayHighlight': True,
}

class AddTripForm(forms.Form):
	purpose = forms.CharField(label='Cel wyjazdu', max_length=255)
	begin_date = forms.DateField(label='Rozpoczęcie', widget=DateWidget(
		options=dateOptions))
	description = forms.CharField(label='Opis', widget=forms.Textarea)

class AddEmployeeForm(ModelForm):
	class Meta:
		model = BusinessTripEmployee
		exclude = ('employee', 'business_trip', 'status')
		widgets = {
			'begin_date': DateWidget(options=dateOptions),
			'end_date': DateWidget(options=dateOptions),
			'description': forms.Textarea,
		}

class AddRouteForm(ModelForm):
	class Meta:
		model = BusinessTripRoute
		exclude = ('settlement',)
		widgets = {
			'begin_time': DateTimeWidget(options=dateTimeOptions),
			'end_time': DateTimeWidget(options=dateTimeOptions),
		}

class AddAllowanceForm(ModelForm):
	class Meta:
		model = BusinessTripAllowance
		exclude = ('settlement', 'is_first_day',)
		widgets = {
			'begin_time': DateTimeWidget(options=dateTimeOptions),
			'end_time': DateTimeWidget(options=dateTimeOptions),
		}


class AddFareForm(ModelForm):

	def __init__(self, pk, *args, **kwargs):
		super(AddFareForm, self).__init__(*args, **kwargs)
		self.fields['route'].queryset = BusinessTripRoute.objects.filter(
			settlement__trip_employee__business_trip=pk)

	class Meta:
		model = BusinessTripInvoiceFare
		exclude = ('settlement',)

class AddAccomodationForm(ModelForm):

	def __init__(self, pk, *args, **kwargs):
		super(AddAccomodationForm, self).__init__(*args, **kwargs)
		self.fields['overnight'].queryset = BusinessTripAllowance.objects.filter(
			settlement__trip_employee__business_trip=pk)

	class Meta:
		model = BusinessTripInvoiceAccomodation
		exclude = ('settlement',)

class AddOtherForm(ModelForm):
	class Meta:
		model = BusinessTripInvoiceOther
		exclude = ('settlement',)

class AddMilageForm(ModelForm):

	def __init__(self, pk, *args, **kwargs):
		super(AddMilageForm, self).__init__(*args, **kwargs)
		self.fields['route'].queryset = BusinessTripRoute.objects.filter(
			settlement__trip_employee__business_trip=pk)
		self.fields['name'].initial = pk

	class Meta:
		model = BusinessTripInvoiceMilage
		exclude = ('settlement',)

trips/templates/add_allowance.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

	<div class="col-md-4 col-md-offset-4">
		<form action="" method="post">
			{% csrf_token %}
			{{ form|crispy }}
			<input class="btn btn-primary" type="submit" value="Dodaj" />
		</form>
	</div>

{% endblock %}

trips/templates/add_cost.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}


	<div class="col-md-4 col-md-offset-4">
		<form action="/trips/add_cost/{{ pk }}/{{ type }}/" method="post" enctype="multipart/form-data">
			{% csrf_token %}
			{{ form|crispy }}
			<input class="btn btn-primary" type="submit" value="Dodaj" />
		</form>
	</div>

{% endblock %}

trips/templates/add_employee.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

	<div class="col-md-5 col-md-offset-4">
		<form action="/trips/add_employee/{{ pk }}/" method="post">
			{% csrf_token %}
			{{ form|crispy }}
			<input class="btn btn-primary" type="submit" value="Wyślij" />
		</form>
	</div>

{% endblock %}

trips/templates/add_route.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

	<div class="col-md-5 col-md-offset-4">
		<form action="/trips/add_route/{{ pk }}/" method="post">
			{% csrf_token %}
			{{ form|crispy }}
			<input class="btn btn-primary" id="submit" type="submit" value="Dodaj" />
		</form>
	</div>
	
{% endblock %}

trips/templates/add_trip.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

	<div class="col-md-5 col-md-offset-4">
		<form action="/trips/add_trip/" method="post">
			{% csrf_token %}
			{{ form|crispy }}
			<input class="btn btn-primary" type="submit" value="Wyślij" />
		</form>
	</div>

{% endblock %}

trips/templates/settlement.html
{% extends "base.html" %}

{% block content %}
  <div class="container-fluid">
    <div class="col-md-9">
      <div class="container-fluid">
        <div class="panel panel-default">
          <div class="panel-heading" id="headingOne">
            <a role="button" data-toggle="collapse" class="btn btn-default" href="#collapseOne" aria-expanded="false" aria-controls="collapseOne"><h5><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Trasy</h5></a>
            <a class="btn btn-primary pull-right" href="/trips/add_route/{{ pk }}/">Dodaj</a>
          </div>
          <div class="collapse in" id="collapseOne">
            <table class="table table-condensed table-hover">
              <tr>
                <th>Wyjazd</th>
                <th>Czas</th>
                <th>Przyjazd</th>
                <th>Czas</th>
                <th>Środek transportu</th>
                <th>Usuń</th>
              </tr>
              {% for route in route_list %}
                <tr>        
                  <td>{{ route.begin }}</td>
                  <td>{{ route.begin_time }}</td>
                  <td>{{ route.end }}</td>
                  <td>{{ route.end_time }}</td>
                  <td>{{ route.get_transportation_display }}</td>
                  <td>
                    <!--
                    <button class="btn btn-default" aria-label="remove">
                      <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                    </button>
                    -->
                    <a href="/trips/delete_route/{{ pk }}/{{ route.id }}"><img src="{{ STATIC_URL }}/images/document_delete.png" alt="x" height="18" width="18"></a></td>
                </tr>
              {% endfor %}
            </table>
          </div> <!-- /.div.collapseOne -->
        </div> <!-- /.panel -->
      </div> <!-- /.container-fluid -->
      <div class="container-fluid">
        <div class="panel panel-default">
          <div class="panel-heading" id="headingTwo">
            <a role="button" data-toggle="collapse" class="btn btn-default" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo"><h5><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Diety</h5></a>
            <a class="btn btn-primary pull-right" href="/trips/add_allowance/{{ pk }}/">Dodaj</a>
          </div>
          <div class="collapse in" id="collapseTwo">
            <table class="table table-condensed table-hover">
              <tr>
                <th>Początek</th>
                <th>Koniec</th>
                <th>Ryczałt dojazdy</th>
                <th>Ryczałt noclegi</th>
                <th>Dieta</th>
                <th>Razem</th>
                <th>Modyfikuj</th>
                <th>Usuń</th>
              </tr>
              {% for allowance in allowance_list %}
              <tr>        
                <td>{{ allowance.begin_time }}</td>
                <td>{{ allowance.end_time }}</td>
                <td>{{ allowance.commute_lump|floatformat:2 }}</td>
                <td>{{ allowance.accomodation_lump|floatformat:2 }}</td>
                <td>{{ allowance.allowance|floatformat:2 }}</td>
                <td>{{ allowance.total_allowance|floatformat:2 }}</td>
                <td><a href="/trips/update_allowance/{{ pk }}/{{ allowance.id }}"><img src="{{ STATIC_URL }}/images/document_edit.png" alt="mod" height="18" width="18"></a></td>
                <td><a href="/trips/delete_allowance/{{ pk }}/{{ allowance.id }}"><img src="{{ STATIC_URL }}/images/document_delete.png" alt="x" height="18" width="18"></a></td>
              </tr>
              {% endfor %}
              <tr>
                <td></td>
                <td></td>
                <th>{{ settlement.commute_lump_total|floatformat:2 }}</th>
                <th>{{ settlement.accomodation_lump_total|floatformat:2 }}</th>
                <th>{{ settlement.allowance_total|floatformat:2 }}</th>
                <th>{{ settlement.total_total|floatformat:2 }}</th>
                <td></td>
                <td></td>
             </tr> 
            </table>
          </div>
        </div>
      </div> <!-- /.container-fluid -->
      <div class="container-fluid">
        <div class="panel panel-default">
          <div class="panel-heading" id="headingThree">
            <a role="button" data-toggle="collapse" class="btn btn-default" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree"><h5><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Koszty</h5></a>
            <!-- Single button -->
            <div class="btn-group pull-right">
              <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Dodaj <span class="caret"></span>
              </button>
              <ul class="dropdown-menu">
                <li><a href="/trips/add_cost/{{ pk }}/3/">Dodaj przejazd</a></li>
                <li><a href="/trips/add_cost/{{ pk }}/2/">Dodaj nocleg</a></li>
                <li><a href="/trips/add_cost/{{ pk }}/1/">Dodaj kilometrówkę</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="/trips/add_cost/{{ pk }}/0/">Pozostały koszt</a></li>
              </ul>
            </div>
          </div>
          <div class="collapse in" id="collapseThree">
            <table class="table table-condensed table-hover">
              <tr>
                <th>Nazwa</th>
                <th>Kwota</th>
                <th>Usuń</th>
              </tr>
              {% for invoice in invoice_list %}
                <tr>        
                  <td>{{ invoice.name }}</td>
                  <td>{{ invoice.amount }}</td>
                  <td><a href="/trips/delete_cost/{{ pk }}/{{ invoice.id }}"><img src="{{ STATIC_URL }}/images/document_delete.png" alt="x" height="18" width="18"></a></td>
                </tr>
              {% endfor %}
              <tr>
                <td></td>
                <th>{{ settlement.invoice_total|floatformat:2 }}</th>
                <td></td>
              </tr>
            </table>
          </div>
        </div>
      </div> <!-- /.container-fluid -->
    </div> <!-- /.col-md-9 -->
    <div class="col-md-3 text-info">
      <div class="jumbotron" data-spy="affix">
        <h3>Rozliczenie nr: {{ pk }}</h3>
        <h4>Kwota: {{ settlement.settlement_total|floatformat:2 }}</br>
        Status: {{ settlement.get_status_display}}</h4>
      </div>
    </div> <!-- /.col-md-3 -->
  </div> <!-- /.container-fluid -->

{% endblock %}

trips/templates/trips.html
{% extends "base.html" %}

{% block content %}

  <div class="container-fluid">
    <a class="btn btn-primary pull-right" href="/trips/add_trip/">Dodaj</a>
    <br><br>
    <table class="table table-condensed table-hover">
      <tr>
        <th>Delegacja</th>
        <th>Data</th>
      </tr>
      <tr>
        {% for trip in object_list %}
          <tr>
            <td><a class="btn btn-link btn-block" href="/trips/{{ trip.id }}/">{{ trip.purpose }}
              </a></td>
            <td>{{ trip.begin_date }}</td>
          </tr>
        {% endfor %}
      </tr>
    </table>
  </div>
  <div class="container-fluid">
    {% if is_paginated %}
      <nav>
        <ul class="pager">
          {% if page_obj.has_previous %}
            <li class="previous"><a href="?page={{ page_obj.previous_page_number }}"><span aria-hidden="true">&larr;</span> Newer</a></li>
          {% else %}
            <li class="previous disabled"><a href="#"><span aria-hidden="true">&larr;</span> Newer</a></li>
          {% endif %}
          {% if page_obj.has_next %}
            <li class="next"><a href="?page={{ page_obj.next_page_number }}">Older <span aria-hidden="true">&rarr;</span></a></li>
          {% else %}
            <li class="next disabled"><a href="#">Older <span aria-hidden="true">&rarr;</span></a></li>
          {% endif %}
        </ul>
      </nav>
    {% endif %}
  </div>

{% endblock %}

trips/templates/trips_detail.html
{% extends "base.html" %}

{% block content %}

  <div class="container-fluid">
    <h2>{{ object.purpose }}</h2>
    <h4>{{ object.begin_date }}</h4>
    {% if is_part %}
      <a class="btn btn-primary pull-right" href="/trips/settlement/{{ object.pk }}/">Rozlicz</a>
    {% else %}
      <a class="btn btn-primary pull-right" href="/trips/add_employee/{{ object.pk }}/">Dołącz</a>
    {% endif %}
  </div>
  <div class="container-fluid">
    <div class="panel panel-default">
      <!-- Default panel contents -->
      <div class="panel-heading"><strong>Uczestnicy</strong></div>
      <div class="panel-body"><p>{{ object.description }}</p></div>
      <!-- Table -->
      <table class="table table-hover">
        <tr>
          <th>Nazwisko</th>
          <th>Imię</th>
          <th>Stanowisko</th>
          <th>Początek</th>
          <th>Koniec</th>
          <th>Status</th>
        </tr>
        <tr>
          {% for person in trip_employees %}
            <tr>
            <!--
              <td><a href="/trips/{{ trip.id }}/">{{ trip.purpose }}
                </a></td>
            -->
              <td>{{ person.employee.last_name }}</td>
              <td>{{ person.employee.first_name }}</td>
              <td>{{ person.employee.user.position }}</td>
              <td>{{ person.begin_date|date:"d.m.Y" }}</td>
              <td>{{ person.end_date|date:"d.m.Y" }}</td>
              <td>{{ person.get_status_display }}</td>
            </tr>
          {% endfor %}
        </tr>
      </table>
  </div>
  <!--
	<div class="section">
		<h2>{{ object.purpose }}</h2>
		<h4>{{ object.begin_date }}</h4>
	</div>
	<div>
		<div class="button"><a href="/trips/add_employee/{{ object.pk }}/">
			Dodaj wniosek</a></div>
		<div class="button"><a href="/trips/settlement/{{ object.pk }}/">
			Rozlicz delegację</a></div>
	</div>
	<div class="section">
		<div class="header">Uczestnicy</div>
		<table>
			<tr>
				<th>Nazwisko</th>
				<th>Imię</th>
				<th>Stanowisko</th>
				<th>Początek</th>
				<th>Koniec</th>
				<th>Status</th>
			</tr>
			<tr>
				{% for person in trip_employees %}
					<tr>
          -->
					<!--
						<td><a href="/trips/{{ trip.id }}/">{{ trip.purpose }}
							</a></td>
					-->
          <!--
						<td>{{ person.employee.last_name }}</td>
						<td>{{ person.employee.first_name }}</td>
						<td>{{ person.employee.user.position }}</td>
						<td>{{ person.begin_date|date:"d.m.Y" }}</td>
						<td>{{ person.end_date|date:"d.m.Y" }}</td>
						<td>{{ person.get_status_display }}</td>
					</tr>
				{% endfor %}
			</tr>
		</table>

		<p> {{ object.description }}</p>
		
	</div>
  -->

{% endblock %}